#!/usr/bin/env bash
# Generates local, git-ignored Mosquitto credentials for SIM-003 development.
# Safe to re-run — it recreates local/passwd and local/acl from scratch.
set -euo pipefail

cd "$(dirname "$0")/.."  # infra/sim-003-mosquitto/

mkdir -p local
rm -f local/passwd

PUB_PASSWORD="${SIM003_MQTT_PUBLISHER_PASSWORD:-$(openssl rand -base64 18)}"
SUB_PASSWORD="${SIM003_MQTT_SUBSCRIBER_PASSWORD:-$(openssl rand -base64 18)}"

mosquitto_passwd -b -c local/passwd sim003-publisher "$PUB_PASSWORD"
mosquitto_passwd -b local/passwd sim003-subscriber "$SUB_PASSWORD"

cp acl.example local/acl

cat > local/.env.generated <<EOF
# Generated by generate-credentials.sh — git-ignored. Copy relevant values
# into services/sim-003-mqtt/.env (also git-ignored).
MQTT_PUBLISHER_USERNAME=sim003-publisher
MQTT_PUBLISHER_PASSWORD=${PUB_PASSWORD}
MQTT_SUBSCRIBER_USERNAME=sim003-subscriber
MQTT_SUBSCRIBER_PASSWORD=${SUB_PASSWORD}
EOF

echo "Generated local/passwd, local/acl, and local/.env.generated"
echo "Credentials are git-ignored. Copy local/.env.generated values into services/sim-003-mqtt/.env"
